### ISSUE TITLE
Throws raw error if target folder doesn't exist

### ISSUE THREAD

**Issue by HeinousTugboat** [bitburner-official/bitburner-filesync#17]
I cloned bitburner-official/typescript-template and ran this tool and this was the output:
![image](https://user-images.githubusercontent.com/15902166/193375542-0f9ee1ff-67a3-42fe-abbe-7a841c7d33ae.png)

Should probably catch this error and handle it.

**Comment by Hoekstraa** [comment]
Yeah, have had that happen before.
Handling it with a procedure like below seems fitting:

*it happens*  
ask user to create folder, y/n
*if y* make folder
*if n or error*, exit, with n silently, with error by printing error before exiting
