### ISSUE TITLE
"This is not the tsc command you are looking for"

### ISSUE THREAD

**Issue by x3cion** [bitburner-official/bitburner-filesync#34]
In the code uploaded to npm for `bitburner-filesync`, `tsc` has been added in `dependencies`, but in the repo here, it never was. This causes above error. Unless really needed, please remove the ´tsc` dependency from the npm package. `tsc` command is already provided by `typescript`

**Comment by Hoekstraa** [comment]
Removed! Version is now 1.2.0-beta4.

![Screenshot from 2023-08-29 10-04-24](https://github.com/bitburner-official/bitburner-filesync/assets/19653491/f9474e81-0d79-439b-902e-b18419efc7e2)
