### ISSUE TITLE
Add linting

### ISSUE THREAD

**Issue by Hoekstraa** [bitburner-official/bitburner-filesync#6]
A linter for the code would be very nice to have.
You don't necessarily have to fix all linting issues within the PR adding the linter.
But you do have to add it to the package.json as a `npm run lint` option.

**Comment by Dun-sin** [comment]
hi, can i work on this?

**Comment by Hoekstraa** [comment]
You can. More info: ESLint is what the mother-project ([Bitburner](https://github.com/danielyxie/bitburner)) uses, so keeping this project in line with that would be nice.

Note: during Hacktoberfest, asking for working on something does not give you lone rights on getting your PR merged.
Have fun!

**Comment by Dun-sin** [comment]
sure

**Comment by Dun-sin** [comment]
can i be assigned?

**Comment by Pustur** [comment]
Hi @Hoekstraa, 

I see that the original PR was not merged due to the migration to typescript.  
I'd like to work on this if @Dun-sin doesn't mind.

Thanks in advance
