### ISSUE TITLE
Add formatter

### ISSUE THREAD

**Issue by Hoekstraa** [bitburner-official/bitburner-filesync#7]
Adding a formatter would be good for code quality.
Please only commit the changes for adding the formatter if you make a PR for this issue. I'll run the formatter myself.
But you do have to add it to the package.json as a `npm run formatter` option besides adding it as a dependency.

**Comment by Pustur** [comment]
Hi @Hoekstraa,  
I'd like to work on this. Would [prettier](https://prettier.io/) be ok for you?

**Comment by Hoekstraa** [comment]
Prettier would be perfect!

You can also use [Bitburner](https://github.com/danielyxie/bitburner) as a reference for configuration if you do.
